#pragma warning disable CA1305, CA1725
using System.ComponentModel.DataAnnotations; using System.Data; using LibrarySystem.Application.Catalog; using LibrarySystem.Application.Security; using LibrarySystem.Domain.Catalog; using LibrarySystem.Infrastructure.Auditing; using LibrarySystem.Infrastructure.Catalog; using LibrarySystem.Infrastructure.Data; using Microsoft.EntityFrameworkCore;
namespace LibrarySystem.Services.Catalog;
public sealed class AcquisitionService(ApplicationDbContext db,ICurrentUser user):IAcquisitionService
{
 public async Task<IReadOnlyCollection<AcquisitionDto>> ListAsync(CancellationToken t=default){Staff();return (await Query().AsNoTracking().OrderByDescending(x=>x.CreatedAtUtc).Take(500).ToListAsync(t)).Select(Map).ToArray();}
 public async Task<AcquisitionDto> CreateAsync(string orderNumber,long bookId,AcquisitionSource source,string? donationSource,int quantity,decimal unitCost,CancellationToken t=default){Staff();if(string.IsNullOrWhiteSpace(orderNumber)||quantity<1||unitCost<0)throw new ValidationException("Reference number, positive quantity, and valid cost are required.");if(!Enum.IsDefined(source))throw new ValidationException("Invalid source.");if(source==AcquisitionSource.Donation&&string.IsNullOrWhiteSpace(donationSource))throw new ValidationException("Donations require a source.");var book=await db.Books.FindAsync([bookId],t)??throw new ValidationException("Book title not found.");var x=new AcquisitionRecord{OrderNumber=orderNumber.Trim(),Book=book,Source=source,DonationSource=Normalize(donationSource),QuantityOrdered=quantity,UnitCost=unitCost,Status=AcquisitionStatus.Ordered};db.Add(x);await db.SaveChangesAsync(t);Audit("AcquisitionCreated",x.Id,x.OrderNumber);await db.SaveChangesAsync(t);return Map(x);}
 public async Task ReceiveAsync(long id,string barcode,int? shelfId,byte[] rowVersion,CancellationToken t=default){Staff();await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,t);var x=await Query().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();if(x.Status==AcquisitionStatus.Cancelled||x.Receipts.Count>=x.QuantityOrdered)throw new ValidationException("This record cannot receive another copy.");db.Entry(x).Property(y=>y.RowVersion).OriginalValue=rowVersion;if(string.IsNullOrWhiteSpace(barcode)||await db.BookCopies.AnyAsync(y=>y.Barcode==barcode.Trim(),t))throw new ValidationException("A unique barcode is required.");if(shelfId.HasValue&&!await db.ShelfLocations.AnyAsync(y=>y.Id==shelfId&&y.IsActive,t))throw new ValidationException("Select an active shelf.");var copy=new BookCopy{BookId=x.BookId,Book=x.Book,Barcode=barcode.Trim(),ShelfLocationId=shelfId,Status=BookCopyStatus.Available,Condition=BookCondition.New,AcquisitionDate=DateOnly.FromDateTime(DateTime.UtcNow),AcquisitionPrice=x.UnitCost};db.BookCopies.Add(copy);x.Receipts.Add(new AcquisitionReceipt{AcquisitionRecord=x,BookCopy=copy,ReceivedByUserId=user.UserId});x.Status=x.Receipts.Count>=x.QuantityOrdered?AcquisitionStatus.Received:AcquisitionStatus.PartiallyReceived;await db.SaveChangesAsync(t);Audit("AcquisitionReceived",x.Id,$"Copy: {copy.Barcode}");await db.SaveChangesAsync(t);await tx.CommitAsync(t);}
 public async Task SetStatusAsync(long id,AcquisitionStatus status,byte[] rowVersion,CancellationToken t=default){Staff();if(status is not AcquisitionStatus.Ordered and not AcquisitionStatus.Cancelled)throw new ValidationException("Only Ordered or Cancelled may be selected manually.");var x=await Query().SingleOrDefaultAsync(x=>x.Id==id,t)??throw new KeyNotFoundException();db.Entry(x).Property(y=>y.RowVersion).OriginalValue=rowVersion;if(x.Receipts.Count>0&&status==AcquisitionStatus.Cancelled)throw new ValidationException("A record with receipts cannot be cancelled.");x.Status=status;Audit("AcquisitionStatusChanged",id,status.ToString());await db.SaveChangesAsync(t);}
 public async Task<AcquisitionBudgetDto> GetBudgetAsync(int year,CancellationToken t=default){Staff();var allocated=await db.AcquisitionBudgets.Where(x=>x.Year==year).Select(x=>(decimal?)x.AllocatedAmount).SingleOrDefaultAsync(t)??0;var spent=await db.AcquisitionReceipts.Where(x=>x.ReceivedAtUtc.Year==year&&x.AcquisitionRecord.Source==AcquisitionSource.Purchase).SumAsync(x=>(decimal?)x.AcquisitionRecord.UnitCost,t)??0;return new(){Year=year,Allocated=allocated,Spent=spent};}
 public async Task SetBudgetAsync(int year,decimal amount,CancellationToken t=default){Staff();if(year<2000||year>2200||amount<0)throw new ValidationException("Enter a valid year and non-negative budget.");var x=await db.AcquisitionBudgets.SingleOrDefaultAsync(x=>x.Year==year,t);if(x is null){x=new AcquisitionBudget{Year=year};db.Add(x);}x.AllocatedAmount=amount;await db.SaveChangesAsync(t);Audit("AcquisitionBudgetSet",x.Id,$"{year}: {amount:F2}");await db.SaveChangesAsync(t);}
 private IQueryable<AcquisitionRecord> Query()=>db.AcquisitionRecords.Include(x=>x.Book).Include(x=>x.Receipts); private static AcquisitionDto Map(AcquisitionRecord x)=>new(){Id=x.Id,OrderNumber=x.OrderNumber,BookId=x.BookId,BookTitle=x.Book.Title,Source=x.Source,DonationSource=x.DonationSource,QuantityOrdered=x.QuantityOrdered,QuantityReceived=x.Receipts.Count,UnitCost=x.UnitCost,Status=x.Status,CreatedAtUtc=x.CreatedAtUtc,RowVersion=x.RowVersion}; private static string? Normalize(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim(); private void Staff(){if(!user.IsInRole(RoleNames.Administrator)&&!user.IsInRole(RoleNames.Librarian))throw new UnauthorizedAccessException();} private void Audit(string action,long id,string? details)=>db.AuditLogs.Add(new AuditLog{ActorUserId=user.UserId,Action=action,TargetType="Acquisition",TargetId=id.ToString(),Details=details});
}
