#pragma warning disable CA1305
using System.ComponentModel.DataAnnotations; using System.Data; using LibrarySystem.Application.Catalog; using LibrarySystem.Application.Security; using LibrarySystem.Domain.Catalog; using LibrarySystem.Infrastructure.Auditing; using LibrarySystem.Infrastructure.Catalog; using LibrarySystem.Infrastructure.Data; using Microsoft.EntityFrameworkCore;
namespace LibrarySystem.Services.Catalog;
public sealed class InventoryService(ApplicationDbContext db,ICurrentUser user):IInventoryService
{
 public async Task<IReadOnlyCollection<InventorySessionDto>> ListAsync(CancellationToken token=default){Staff();var sessions=await db.InventorySessions.AsNoTracking().OrderByDescending(x=>x.StartedAtUtc).ToListAsync(token);var result=new List<InventorySessionDto>();foreach(var x in sessions)result.Add(await Map(x,false,token));return result;}
 public async Task<InventorySessionDto> StartAsync(string name,CancellationToken token=default){Staff();if(string.IsNullOrWhiteSpace(name)||name.Trim().Length>200)throw new ValidationException("A session name of 200 characters or fewer is required.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,token);var session=new InventorySession{Name=name.Trim(),CreatedByUserId=user.UserId};var ids=await db.BookCopies.Where(x=>x.Status!=BookCopyStatus.Withdrawn).Select(x=>x.Id).ToListAsync(token);foreach(var id in ids)session.ExpectedCopies.Add(new InventoryExpectedCopy{InventorySession=session,BookCopyId=id,BookCopy=null!});db.InventorySessions.Add(session);await db.SaveChangesAsync(token);Audit("InventoryStarted",session.Id,$"Expected copies: {ids.Count}");await db.SaveChangesAsync(token);await tx.CommitAsync(token);return await Map(session,false,token);}
 public async Task<InventorySessionDto?> GetAsync(long id,CancellationToken token=default){Staff();var x=await db.InventorySessions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,token);return x is null?null:await Map(x,true,token);}
 public async Task ScanAsync(long sessionId,string barcode,CancellationToken token=default){Staff();if(string.IsNullOrWhiteSpace(barcode))throw new ValidationException("A barcode is required.");var session=await db.InventorySessions.SingleOrDefaultAsync(x=>x.Id==sessionId,token)??throw new KeyNotFoundException();if(session.Status!=InventorySessionStatus.Open)throw new ValidationException("This inventory session is complete.");var copy=await db.BookCopies.SingleOrDefaultAsync(x=>x.Barcode==barcode.Trim(),token)??throw new ValidationException("The barcode does not exist.");if(!await db.InventoryExpectedCopies.AnyAsync(x=>x.InventorySessionId==sessionId&&x.BookCopyId==copy.Id,token))throw new ValidationException("This copy was not in the expected list when the session began.");if(!await db.InventoryScans.AnyAsync(x=>x.InventorySessionId==sessionId&&x.BookCopyId==copy.Id,token)){db.InventoryScans.Add(new InventoryScan{InventorySession=session,BookCopy=copy,FoundByUserId=user.UserId});Audit("InventoryCopyFound",copy.Id,$"Session: {sessionId}");await db.SaveChangesAsync(token);}}
 public async Task CompleteAsync(long sessionId,CancellationToken token=default){Staff();var x=await db.InventorySessions.SingleOrDefaultAsync(x=>x.Id==sessionId,token)??throw new KeyNotFoundException();if(x.Status==InventorySessionStatus.Completed)return;x.Status=InventorySessionStatus.Completed;x.CompletedAtUtc=DateTime.UtcNow;Audit("InventoryCompleted",sessionId,null);await db.SaveChangesAsync(token);}
 public async Task ReconcileMissingAsync(long sessionId,long copyId,CancellationToken token=default){Staff();var session=await db.InventorySessions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==sessionId,token)??throw new KeyNotFoundException();if(session.Status!=InventorySessionStatus.Completed)throw new ValidationException("Complete the inventory session before reconciling missing copies.");if(await db.InventoryScans.AnyAsync(x=>x.InventorySessionId==sessionId&&x.BookCopyId==copyId,token))throw new ValidationException("This copy was found and is not a discrepancy.");var copy=await db.BookCopies.SingleOrDefaultAsync(x=>x.Id==copyId,token)??throw new KeyNotFoundException();if(copy.Status is BookCopyStatus.OnLoan or BookCopyStatus.Reserved or BookCopyStatus.Withdrawn)throw new ValidationException("A circulated, reserved, or withdrawn copy cannot be reconciled as missing.");copy.Status=BookCopyStatus.Lost;copy.UpdatedAtUtc=DateTime.UtcNow;Audit("InventoryMissingReconciled",copyId,$"Session: {sessionId}; marked Lost");await db.SaveChangesAsync(token);}
 public async Task WithdrawAsync(long copyId,string reason,CancellationToken token=default){Staff();if(string.IsNullOrWhiteSpace(reason)||reason.Trim().Length>500)throw new ValidationException("A withdrawal reason is required.");var copy=await db.BookCopies.SingleOrDefaultAsync(x=>x.Id==copyId,token)??throw new KeyNotFoundException();if(copy.Status is BookCopyStatus.OnLoan or BookCopyStatus.Reserved)throw new ValidationException("Return or cancel circulation before withdrawing this copy.");if(await db.CopyWithdrawals.AnyAsync(x=>x.BookCopyId==copyId,token))return;copy.Status=BookCopyStatus.Withdrawn;copy.UpdatedAtUtc=DateTime.UtcNow;db.CopyWithdrawals.Add(new CopyWithdrawal{BookCopy=copy,Reason=reason.Trim(),ActorUserId=user.UserId});Audit("CopyWithdrawn",copyId,reason.Trim());await db.SaveChangesAsync(token);}
 public async Task WithdrawByBarcodeAsync(string barcode,string reason,CancellationToken token=default){Staff();if(string.IsNullOrWhiteSpace(barcode))throw new ValidationException("A barcode is required.");var id=await db.BookCopies.Where(x=>x.Barcode==barcode.Trim()).Select(x=>(long?)x.Id).SingleOrDefaultAsync(token)??throw new ValidationException("The barcode does not exist.");await WithdrawAsync(id,reason,token);}
 private async Task<InventorySessionDto> Map(InventorySession x,bool details,CancellationToken t){var expected=await db.InventoryExpectedCopies.AsNoTracking().Where(y=>y.InventorySessionId==x.Id).Select(y=>new{y.BookCopyId,y.BookCopy.Barcode,y.BookCopy.Book.Title,Shelf=y.BookCopy.ShelfLocation!=null?y.BookCopy.ShelfLocation.Code:null,y.BookCopy.Status}).ToListAsync(t);var scans=await db.InventoryScans.AsNoTracking().Where(y=>y.InventorySessionId==x.Id).ToDictionaryAsync(y=>y.BookCopyId,y=>(DateTime?)y.FoundAtUtc,t);var copies=details?expected.Select(y=>new InventoryCopyDto{CopyId=y.BookCopyId,Barcode=y.Barcode,Title=y.Title,Shelf=y.Shelf,Status=y.Status,Found=scans.ContainsKey(y.BookCopyId),FoundAtUtc=scans.GetValueOrDefault(y.BookCopyId)}).OrderBy(y=>y.Found).ThenBy(y=>y.Title).ToArray():[];return new InventorySessionDto{Id=x.Id,Name=x.Name,Status=x.Status,StartedAtUtc=x.StartedAtUtc,CompletedAtUtc=x.CompletedAtUtc,ExpectedCount=expected.Count,FoundCount=scans.Count,MissingCount=expected.Count-scans.Count,Copies=copies};}
 private void Staff(){if(!user.IsInRole(RoleNames.Administrator)&&!user.IsInRole(RoleNames.Librarian))throw new UnauthorizedAccessException();} private void Audit(string action,long id,string? details)=>db.AuditLogs.Add(new AuditLog{ActorUserId=user.UserId,Action=action,TargetType="Inventory",TargetId=id.ToString(),Details=details});
}
